[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"


[project]
name = "zak-nlptk"
version = "0.2.0"

description = "A lightweight Python NLP toolkit for pretraining (text normalization, text segmentation, and bpe tokenization), tf-idf feature extraction, and text classification (naive bayes)."

readme = "README.md"

requires-python = ">=3.10"

license = { file = "LICENSE" }

authors = [
    { name = "Ihimbru Zadolf Ongum" }
]

keywords = [
    "nlp",
    "natural-language-processing",
    "tokenization",
    "bpe",
    "byte-pair-encoding",
    "lemmatization",
    "text-normalization",
    "text-segmentation",
    "machine-learning",
    "term frequency inverse document frequency",
    "tf-idf",
    "naive bayes classifier"
]

classifiers = [
    "Development Status :: 3 - Alpha",

    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",

    "License :: OSI Approved :: MIT License",

    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",

    "Topic :: Text Processing :: Linguistic",
    "Topic :: Scientific/Engineering :: Artificial Intelligence"
]

dependencies = [
    "numpy",
    "pandas"
]

[project.optional-dependencies]
dev = [
    "pytest>=8.0"
]


[tool.setuptools]
package-dir = { "" = "src" }


[tool.setuptools.packages.find]
where = ["src"]


[tool.setuptools.package-data]
zak_nlptk = [
    "data/*.txt",
    "data/*.json"
]